services:
  signal-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: signal-analyzer
    mem_limit: 512m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "<server-ip>:8501:8501"
    volumes:
      - fast_data:/data
    devices:

    restart: unless-stopped
volumes:
  fast_data: